Repository owncloud/twofactor_totp, pull requests merged in 2018-09, with the labels that each got.

#53 add commands to change verified state of secret
  .travis.yml
  appinfo/info.xml
  lib/Command/SetSecretVerificationStatusCommand.php
  lib/Db/TotpSecretMapper.php
  tests/phpunit.xml
  tests/unit/Command/SetSecretVerificationStatusCommandTest.php
  tests/unit/Db/TotpSecretMapperTest.php
Labels: 3 - To review

#54 add PHP7.2 to tests
  .travis.yml
  appinfo/info.xml
Labels: 3 - To review, QA-team

#63 do not allow multiple uses of the same key
  appinfo/database.xml
  lib/Db/TotpSecret.php
  lib/Db/TotpSecretMapper.php
  lib/Service/Totp.php
  tests/unit/Service/TotpTest.php
Labels: bug
