Repository owncloud/twofactor_totp, pull requests merged in 2018-11, with the labels that each got.

#78 Move phpunit.xml to top level
  .gitignore
  .travis.yml
  Makefile
  phpunit.xml
  tests/unit/phpunit.xml
Labels: 3 - To review, QA-team

#74 Move CI from travis to drone
  .drone.yml
  Makefile
Labels: 3 - To review, QA-team, dev:acceptance-tests

#80 Bye bye Travis
  .drone.yml
  .travis.yml
  README.md
Labels: 3 - To review, QA-team

#81 drop lock file for vendor-bin dependencies
  .gitignore
  vendor-bin/owncloud-codestyle/composer.lock
Labels: 3 - To review, QA-team, dev:acceptance-tests

#83 Prepare 0.5.2 release
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To review
