Repository owncloud/twofactor_totp, pull requests merged in 2019-07, with the labels that each got.

#124 two factor authentication workflow
  tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
  tests/acceptance/features/lib/VerificationPage.php
  tests/acceptance/features/webUITwoFactorTOTP/keyVerification.feature
Labels: 3 - To review, QA-team, dev:acceptance-tests

#125 twofactor_totp app test against latest tarball
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#126 twofactor_totp app test against 10.2.1 tarball
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#127 bump release-branch and add changelog items
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To review

#130 Release 0.6.0
  CHANGELOG.md
  appinfo/info.xml
Labels: 4 - To release

#134 Implement api tests for OCS v2
  tests/acceptance/features/apiTwoFactorTOTP/steps.feature
Labels: 3 - To review, QA-team, dev:acceptance-tests

#135 Remove stable10 test jobs
  .drone.yml
Labels: 3 - To review, Drone, QA-team
