Repository owncloud/twofactor_totp, pull requests merged in 2019-03, with the labels that each got.

#38 add validate api for totp
  appinfo/routes.php
  lib/Controller/TotpApiController.php
  lib/Provider/TotpProvider.php
  lib/Service/ITotp.php
  lib/Service/Totp.php
  tests/unit/Controller/TotpApiControllerTest.php
  tests/unit/Provider/TotpProviderTest.php
  tests/unit/Service/TotpTest.php
Labels: enhancement

#104 exclude other new CI files from tarball
  Makefile
Labels: 3 - To review, QA-team

#107 Drop PHP 5.6
  .drone.yml
Labels: 3 - To review, QA-team

#108 Adjust composer files for 'drop PHP 5.6'
  appinfo/info.xml
  composer.json
  composer.lock
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team

#109 Release 0.5.3
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To review
