Repository owncloud/twofactor_totp, pull requests merged in 2019-10, with the labels that each got.

#143 Update drone starlark with latest code 20191011
  .drone.starlark
Labels: 3 - To review, Drone, QA-team

#145 Run TOTP acceptance tests on PHP 7.3
  .drone.starlark
  .drone.yml
Labels: 3 - To review, QA-team, dev:acceptance-tests

#146 Bump version number and update changelog
  CHANGELOG.md
  appinfo/info.xml
Labels: 3 - To review

#148 Refactor Makefile dist
  Makefile
Labels: 3 - To review

#149 drone notify on failure
  .drone.starlark
  .drone.yml
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To review, Drone, QA-team

#151 test latest tarball
  .drone.starlark
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests
