Repository owncloud/twofactor_totp, pull requests merged in 2020-03, with the labels that each got.

#163 Pin behat/mink to 1.7.1 and update other acceptance test dependencies
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team, dev:acceptance-tests

#162 symfony updates
  composer.lock
Labels: 3 - To review

#164 remove endroid/qrcode dependency to reduce package size
  appinfo/info.xml
  composer.json
  composer.lock
  lib/Controller/SettingsController.php
  tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
  tests/unit/Controller/SettingsControllerTest.php
Labels: 4 - To release
