Repository owncloud/twofactor_totp, pull requests merged in 2020-12, with the labels that each got.

#201 [Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud
  .drone.star
  .gitignore
  sonar-project.properties
Labels: 3 - To review, QA-team, dev:acceptance-tests

#204 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.star
  phpstan.neon
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To review, QA-team

#205 Update christian-riesen/otp to 2.6
  composer.json
  composer.lock
  lib/Service/Totp.php
  tests/acceptance/features/bootstrap/TwoFactorTOTPContext.php
  tests/unit/Service/TotpTest.php
Labels: dependencies
